# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menu_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_size',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
